server:
  port: 9090

spring:
  application:
    name=MicroserviceApplication-gateway
  profiles:
    active:
      - default
  cloud:
    gateway:
      routes:
        - id: Address
          uri: http://localhost:8081/
          predicates:
            - Path=/book/**
        - id: Student
          uri: http://localhost:8082/
          predicates:
            - Path=/library/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka